project_id = "jnddppqhgfsfltsskwgz"

[functions.seed-test-users]
verify_jwt = false

[functions.drgreen-proxy]
verify_jwt = false

[functions.exchange-rates]
verify_jwt = false

[functions.send-client-email]
verify_jwt = false

[functions.drgreen-health]
verify_jwt = false